とちゅうまでつくった。

diff --git a/lib/common b/lib/common
--- a/lib/common
+++ b/lib/common
@@ -138,6 +138,20 @@ function install_app() {
     echo "done: app install \"$app_name\""
 }
 
+function install_from_collection() {
+    _asserts_env_loaded
+
+    local app_name="$1"
+    local app_path="$GHOOKS_BASEDIR/collection/$app_name"
+
+    if [ -d "$app_path" ]; then
+        echo "cancel: $app_name not found in collection." >&2
+        return 1
+    fi
+
+    install_app "$app_path"
+}
+
 function refresh_app() {
     _asserts_env_loaded
 
@@ -266,9 +280,18 @@ function prune_hooks() {
 function install_git_config() {
     _asserts_env_loaded
 
+    local scope="${1:---global}"
     local hooks_dir=$(abs_path "$GHOOKS_BASEDIR/hooks")
-    echo "change git config(global): core.hooksPath \"$hooks_dir\""
-    git config --global core.hooksPath "$hooks_dir"
+    echo "change git config(${scope:2}): core.hooksPath \"$hooks_dir\""
+    git config "$scope" core.hooksPath "$hooks_dir"
+}
+
+function uninstall_git_config() {
+    _asserts_env_loaded
+
+    local scope="${1:---global}"
+    echo "unset git config(${scope:2}): core.hooksPath"
+    git config "$scope" --unset core.hooksPath
 }
 
 function load_config() {
